// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6yImzahBBInnFjkS5do4Q2ivJRYYRVOE',
    appId: '1:763033977442:web:5be9f51ecbe1bdeee1073b',
    messagingSenderId: '763033977442',
    projectId: 'flutter-project-9ef82',
    authDomain: 'flutter-project-9ef82.firebaseapp.com',
    storageBucket: 'flutter-project-9ef82.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz-2ywj2pgKJP2NQl7YMzhFyvwA_qCm4M',
    appId: '1:763033977442:android:123546666975b205e1073b',
    messagingSenderId: '763033977442',
    projectId: 'flutter-project-9ef82',
    storageBucket: 'flutter-project-9ef82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP_3lFgBGUTMTSTuoDF_Qz_ybuk8K3ObA',
    appId: '1:763033977442:ios:87ff62f2de655e7ee1073b',
    messagingSenderId: '763033977442',
    projectId: 'flutter-project-9ef82',
    storageBucket: 'flutter-project-9ef82.appspot.com',
    androidClientId: '763033977442-s6si6v7iclasghqph27emgvnjsl32hve.apps.googleusercontent.com',
    iosClientId: '763033977442-1uucdbf9ao1u38a7qrv9e7l4t73k0f18.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP_3lFgBGUTMTSTuoDF_Qz_ybuk8K3ObA',
    appId: '1:763033977442:ios:87ff62f2de655e7ee1073b',
    messagingSenderId: '763033977442',
    projectId: 'flutter-project-9ef82',
    storageBucket: 'flutter-project-9ef82.appspot.com',
    androidClientId: '763033977442-s6si6v7iclasghqph27emgvnjsl32hve.apps.googleusercontent.com',
    iosClientId: '763033977442-1uucdbf9ao1u38a7qrv9e7l4t73k0f18.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6yImzahBBInnFjkS5do4Q2ivJRYYRVOE',
    appId: '1:763033977442:web:6be628bf34af37c4e1073b',
    messagingSenderId: '763033977442',
    projectId: 'flutter-project-9ef82',
    authDomain: 'flutter-project-9ef82.firebaseapp.com',
    storageBucket: 'flutter-project-9ef82.appspot.com',
  );
}
